linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - nakedret
    - dupl
    - wsl
    - funlen
    - gocognit
    - goerr113
    - gomnd
    - testpackage
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errcheck
run:
  skip-files:
    - crc32
    - sha1
