dist: trusty
language: go
jobs:
  include:
    - stage: test
      env:
        NAME="gometalinter"
      before_install:
        - go get -u github.com/alecthomas/gometalinter
        - gometalinter --install --update
        - go get github.com/golang/dep/cmd/dep
      install:
        - dep ensure -vendor-only
      script: gometalinter --config=gometalinter.json
    - stage: test
      env:
        NAME="go test"
      sudo: required
      services:
        - mysql
        - rabbitmq
      before_install:
        - go get github.com/golang/dep/cmd/dep
      install:
        - dep ensure -vendor-only
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
      before_script:
        - echo "CREATE DATABASE efes" | mysql
        - echo "GRANT ALL ON efes.* TO travis@'%'" | mysql
        - echo 'FLUSH PRIVILEGES' | mysql
        - mysql efes < schema.sql
        - sudo cp config-travis.toml /etc/efes.toml
      script: goveralls -v -race -package ./...
