[tracker]
debug = true
listen_address = "0.0.0.0:8001"
shutdown_timeout = 5000
[database]
dsn = "mogilefs:123@(efes_mysql_1:3306)/mogilefs"
[server]
debug = true
[amqp]
url = "amqp://guest:guest@efes_rabbitmq_1:5672)/"
