debug = true
[tracker]
listen_address = "0.0.0.0:8001"
shutdown_timeout = "5s"
[database]
dsn = "travis@(localhost:3306)/efes"
[server]
datadir = "/srv/efes/dev1"
listen_address_for_read = "0.0.0.0:8500"
listen_address = "0.0.0.0:8501"
shutdown_timeout = "10s"
clean_disk_file_ttl = "60s"
clean_disk_run_period = "30s"
[amqp]
url = "amqp://guest:guest@localhost:5672/"
[client]
tracker_url = "http://localhost:8001"
chunk_size = "1M"
