version: '3.3'
services:
  db:
    build:
      dockerfile: Dockerfile.db
      context: .
  tracker:
    build:
      dockerfile: Dockerfile.tracker
      context: .
    ports:
      - "8001:8001"
  server1:
    build:
      dockerfile: Dockerfile.server
      context: .
    environment:
      datadir: /srv/mogilefs/dev1
  server2:
    build:
      dockerfile: Dockerfile.server
      context: .
    environment:
      datadir: /srv/mogilefs/dev2
