version: '3.3'
services:
  mysql:
    build:
      dockerfile: Dockerfile-mysql
      context: .
    logging:
      driver: none
  tracker:
    build:
      dockerfile: Dockerfile-tracker
      context: .
    depends_on:
      - mysql
    tty: true
  server1:
    build:
      dockerfile: Dockerfile-server
      context: .
    command: ["1"]
    depends_on:
      - mysql
    tty: true
