version: '3.3'
services:
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    logging:
      driver: none
  test:
    build:
      dockerfile: Dockerfile-test
      context: .
    tty: true
