version: '3.3'
services:
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    logging:
      driver: none
  tracker:
    build:
      dockerfile: Dockerfile-tracker
      context: .
    depends_on:
      - db
    tty: true
  server1:
    build:
      dockerfile: Dockerfile-server
      context: .
    command: ["1"]
    depends_on:
      - db
    tty: true
  server2:
    build:
      dockerfile: Dockerfile-server
      context: .
    command: ["2"]
    depends_on:
      - db
    tty: true
