version: '3.2'
services:
  mysql:
    build:
      dockerfile: Dockerfile-mysql
      context: .
  rabbitmq:
    build:
      dockerfile: Dockerfile-rabbitmq
      context: .
    logging:
      driver: none
  test:
    build:
      dockerfile: Dockerfile-test
      context: .
    tty: true
