version: '3.2'
services:
  mysql:
    build:
      dockerfile: Dockerfile-mysql
      context: .
    logging:
      driver: none
  rabbitmq:
    image: "rabbitmq:3.6"
    entrypoint: rabbitmq-server
    environment:
      HOME: /root
    logging:
      driver: none
  test:
    build:
      dockerfile: Dockerfile-test
      context: .
    tty: true
