version: '3.3'
services:
  db:
    build:
      dockerfile: Dockerfile.db
      context: .
  db_setup:
    entrypoint:
      - "/root/docker-wait-for-db.sh"
      - "efes_db_1"
      - "mogilefs"
      - "123"
      - "mogilefs"
      - "INSERT INTO host (hostid, status, hostname, hostip) VALUES (1, 'alive', 's1', '$EXTERNAL_IP')"
      - "INSERT INTO host (hostid, status, hostname, hostip) VALUES (2, 'alive', 's2', '$EXTERNAL_IP')"
      - "INSERT INTO device (devid, hostid, status) VALUES (1, 1, 'alive')"
      - "INSERT INTO device (devid, hostid, status) VALUES (2, 2, 'alive')"
    build:
      dockerfile: Dockerfile.dbsetup
      context: .
    depends_on:
      - db
  tracker:
    build:
      dockerfile: Dockerfile.tracker
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - db
  server1:
    build:
      dockerfile: Dockerfile.server
      context: .
    environment:
      datadir: /srv/mogilefs/dev1
    depends_on:
      - db
  server2:
    build:
      dockerfile: Dockerfile.server
      context: .
    environment:
      datadir: /srv/mogilefs/dev2
    depends_on:
      - db
