version: '3.3'
services:
  mysql:
    build:
      dockerfile: Dockerfile-mysql
      context: .
    logging:
      driver: none
  test:
    build:
      dockerfile: Dockerfile-test
      context: .
    tty: true
