name: push
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33
      - name: Run tests
        run: make test